# Generated by Django 3.2.4 on 2021-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uid',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2021-06-24', verbose_name='date_created'),
            preserve_default=False,
        ),
    ]
