# Generated by Django 3.2.4 on 2021-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_uid_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='uid',
            name='updated_data',
            field=models.CharField(max_length=200, null=True, verbose_name='updated_data'),
        ),
    ]
