# Generated by Django 3.2.4 on 2021-07-30 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_uid_updated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram chat id'),
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, verbose_name='telegram group id')),
                ('group_type', models.CharField(max_length=10, verbose_name='type of telegram group')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_telegram_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_group',
            },
        ),
    ]
