# Generated by Django 3.2.4 on 2021-07-30 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210730_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='users',
            field=models.ManyToManyField(related_name='user_telegram_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
