# Generated by Django 3.2.4 on 2021-07-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210730_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='telegram chat id'),
        ),
        migrations.CreateModel(
            name='UserSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_owner', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(null=True, related_name='subscriber_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriber',
            },
        ),
    ]
