# Generated by Django 3.2.4 on 2021-07-30 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20210730_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriber',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriber_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
